-- 전체 게시판 조회
SELECT NO, NAME, CONTENT, WRITER, REGDATE
FROM JAVA_FREEBOARD
WHERE DELYN = 'N'
ORDER BY NO;

-- 상세 게시판
SELECT NO, NAME, CONTENT, WRITER, REGDATE
FROM JAVA_FREEBOARD
WHERE NO = 1;

UPDATE JAVA_FREEBOARD
SET DELYN = 'Y'
WHERE NO = 1;

-- insert
INSERT INTO JAVA_FREEBOARD (NO, NAME, CONTENT, WRITER)
VALUES ((SELECT NVL(MAX(NO), 0) + 1 FROM JAVA_FREEBOARD), '제목', '내용', '작성자');

-- update
UPDATE JAVA_FREEBOARD
SET NAME = '이름', CONTENT = '내용'
WHERE NO = 1;

SELECT * FROM JAVA_FREEBOARD;